project:
  name: quickstart-apache-superset
  owner: quickstart-eng@amazon.com
  package_lambda: false
  parameters:
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    QSS3KeyPrefix: 'quickstart-apache-superset/'
  regions:
    - af-south-1
    - ap-east-1
    - ap-south-1
    - ap-northeast-3
    - ap-northeast-2
    - ap-southeast-1
    - ap-southeast-2
    - ap-northeast-1
    - ca-central-1
    # - cn-north-1
    # - cn-northwest-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - eu-south-1
    - eu-west-3
    - eu-north-1
    - me-south-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
tests:
  default:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      SuperSetUserPassword: P!$[taskcat_genpass_12A]
      ClusterName: $[taskcat_genpass_8]
    template: templates/superset-entrypoint-new-vpc.template.yaml
    regions:
    - us-east-1
    #- us-west-2
    #- eu-central-1
    #- eu-north-1
    #- ap-south-1
    #- ap-southeast-1
    #- ap-northeast-1
  secondary:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      SuperSetUserPassword: P!$[taskcat_genpass_12A]
      ClusterName: $[taskcat_genpass_8]
    template: templates/superset-entrypoint-new-vpc.template.yaml
    regions:
    #- us-east-1
    - us-west-2
    #- eu-central-1
    #- eu-north-1
    #- ap-south-1
    #- ap-southeast-1
    #- ap-northeast-1